#' Plot a CrossLink object
#'
#' @param object a CrossLink object
#' @param layout the layout to be plot. Set NULL to plot current active layout
#' @param link a named list of arguments for links. see [ggplot2::geom_segment()]. Set NULL to use default settings, or Set NA to not show.
#' @param cross a named list of arguments for crosses. see [ggplot2::geom_point()]. Set NULL to use default settings, or Set NA to not show.
#' @param label a named list of arguments for node labels. see [ggplot2::geom_text()]. Set NULL to use default settings, or Set NA to not show.
#' @param header a named list of arguments for headers. see [ggplot2::geom_text()]. Set NULL to use default settings, or Set NA to not show.
#' @param add other gg objects to be added to final plot, such as theme(). use list of multiple gg objects to add them all.
#' @param annotation generated by cl_annotation()
#'
#' @return a ggplot2 object
#' @details
#' For link, cross, label, header: "geom" is restricted for setting geom function, such as list(geom = "arc") for link.
#'
#' @import ggplot2
#' @import patchwork
#' @md
#' @export
#'
#' @examples
#'
cl_plot <- function(object, layout = NULL,
                    link = NULL,
                    cross = NULL,
                    label = NULL,
                    header = NULL,
                    add = NULL,
                    annotation = cl_annotation()){
  p_layer <- function(p, list, data_fun, default_aes, default_geom, default_param = NULL){
    if(!identical(list, NA)){
      list$mapping <- override_aes(list$mapping, default_aes)
      list$data <- nullna_default(list$data, data_fun(object, layout))
      params <- setdiff(names(default_param), names(list))
      for (i in params) {
        list[[i]] <- default_param[[i]]
      }
      geom <- paste0("geom_", nullna_default(list$geom, default_geom))
      list$geom <- NULL
      scale <- list$scale
      list$scale <- NULL
      p <- p + do.call(geom, list)
      if(!is.null(scale)) {
        scale_aes = unique(names(scale))
        for(i in seq_along(scale_aes)){
          #p <- p+ eval(parse(text = scale[[scale_aes[i]]])) + ggnewscale::new_scale(scale_aes[i])
          p <- ggplot_add(scale[[scale_aes[i]]], p) + ggnewscale::new_scale(scale_aes[i])
        }
      }

      return(p)
    }else{
      return(p)
    }
  }

  p <- ggplot()
  # link
  p <- p_layer(p,
               link, data_fun = get_link,
               default_aes = aes(x = x, y = y, xend = xend, yend = yend, color = src.cross),
               default_geom = "segment")
  # cross
  p <- p_layer(p,
               cross, data_fun = get_cross,
               default_aes = aes(x = x, y = y, size = degree, color = cross),
               default_geom = "point")
  # label
  p <- p_layer(p,
               label, data_fun = get_cross,
               default_aes = aes_string(x = "x", y = "y", label = object@params$key.by),
               default_geom = "text")
  # header
  if(!identical(suppressWarnings(get_header(object, layout)), NA)){
    p <- p_layer(p,
                 header, data_fun = get_header,
                 default_aes = aes(x = x, y = y, label = header),
                 default_geom = "text", default_param = list(fontface = "bold"))
  }

  # expand
  p <- p +
    scale_x_continuous(expand = expansion(mult = 0.1)) +
    scale_y_continuous(expand = expansion(mult = 0.1))

  # add
  # if(is.ggproto(add)){
  #  p <- ggplot_add(add, p)
  # }
  # 修复这里：将 class(add) == "list" 改为 inherits(add, "list")
  if(inherits(add, "list")){
    for(i in seq_along(add)){
      p <- ggplot_add(add[[i]], p)
    }
  }else if(!is.null(add)){
    p <- ggplot_add(add, p)
  }

  # Annotations
  if(is.list(annotation)){
    cross_coord <- get_cross(object, layout = layout)
    annotation_flag <- 0
    for(i in c("top", "bottom", "left","right")){
      i_p <- annotation[[i]]
      i_b <- annotation[[paste0(i, ".by")]]

      if(!(is.null(i_p) || is.null(i_b))){
        i_axis <- ifelse(i %in% c("top", "bottom"), "x", "y")
        i_axis_ann <- ifelse(layer_scales(i_p)[[i_axis]][["position"]] %in% c("top", "bottom"), "x", "y") # if coord_flip

        i_range <- range(cross_coord[cross_coord$cross == i_b, i_axis])
        i_prange <- ggplot_build(p)$layout$panel_params[[1]][[paste0(i_axis, ".range")]]
        i_expand <- if(i_axis_ann == "x"){
          if(is.numeric(aplot::xrange(i_p))) scale_x_continuous(expand = expansion(mult = abs(i_range - i_prange)/diff(i_prange)))
          else scale_x_discrete(expand = expansion(mult = abs(i_range - i_prange)/diff(i_range)))
        }else{
          if(is.numeric(aplot::yrange(i_p))) scale_y_continuous(expand = expansion(mult = abs(i_range - i_prange)/diff(i_prange)))
          else scale_y_discrete(expand = expansion(mult = abs(i_range - i_prange)/diff(i_range)))
        }
        annotation[[i]] <- i_p + i_expand
        annotation_flag <- annotation_flag + 1
      }else{
        annotation[[paste0(i, ifelse(i %in% c("top", "bottom"), ".height", ".width"))]] <- 0
        annotation[[i]] <- plot_spacer()
      }
    }
    if(annotation_flag > 0){

      p <- annotation[["top"]] + annotation[["left"]] + p + annotation[["right"]] + annotation[["bottom"]] +
        patchwork::plot_layout(ncol = 3, nrow = 3,
                               widths = c(annotation[["left.width"]], 1, annotation[["right.width"]]),
                               heights = c(annotation[["top.height"]], 1, annotation[["bottom.height"]]),
                               guides = "collect",
                               design = c(patchwork::area(1,2,1,2),
                                          patchwork::area(2,1,2,1),
                                          patchwork::area(2,2,2,2),
                                          patchwork::area(2,3,2,3),
                                          patchwork::area(3,2,3,2))
      )
    }
  }

  return(p)
}
